#!/usr/bin/env bash
# generated by Sandbox Console v0.2.0 — do not edit; the extension regenerates it
# sha256: 0481b14739f78f01743dd937d9d3a41b84fcbab96d03a19df706debb4100c90a
#
# Project CLI over the committed sandbox recipe (.sandbox/config.yaml). All values
# (project name, keys, the gitignored local id) are derived at run time, so this file
# is identical across clones and safe to commit. It never contains secret values.
# Windows: run from Git Bash —  bash .sandbox/scripts/sbx.sh <command>
#
# Commands:
#   name [key]                  print the derived instance name (default: the default sandbox)
#   status                      sbx ls filtered to this working copy's instances
#   connect [key]               create from the recipe if absent, then attach (sbx run)
#   stop [key]                  stop, state preserved
#   rm <key> --force            destroy the instance (in-sandbox state is lost)
#   rebuild [key]               docker build --pull -> save -> sbx template load -> rm -> refresh image (FR-053) -> recreate
#   exec <key|runner> -- <cmd>  run a command in the workspace (-w resolved, clone-aware)
#   task <key|runner> "<prompt>" [--bg|--json]
#                               headless claude -p; --bg logs to /tmp, --json prints cost
#   runner-create <slug> [-m 8g] [--cpus 4]
#                               ephemeral clone-mode runner from the default sandbox
#   runner-rm <runner> [--force]
#                               guarded: refuses while work is neither pushed nor fetched
#   runners                     list this working copy's runners
#   secret-github [key|runner]  provision the github secret from the local secret cache
#   version                     print the generator version
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
CFG="$ROOT/.sandbox/config.yaml"
IDF="$ROOT/.sandbox/identity.yaml"

die() { printf 'sbx.sh: %s\n' "$*" >&2; exit 1; }

[ -f "$CFG" ] || die "no .sandbox/config.yaml — define a sandbox first (VS Code: New Sandbox)"

SBX="sbx"
if ! command -v sbx >/dev/null 2>&1; then
  if [ -n "${LOCALAPPDATA:-}" ] && [ -x "${LOCALAPPDATA}/DockerSandboxes/bin/sbx.exe" ]; then
    SBX="${LOCALAPPDATA}/DockerSandboxes/bin/sbx.exe"
  fi
fi

# ---- recipe access (the canonical shape the extension writes) -----------------------

unquote() { sed -e 's/^"\(.*\)"$/\1/' -e "s/^'\(.*\)'\$/\1/"; }

cfg_project() { awk -F': *' '$1=="name" {print $2; exit}' "$CFG" | unquote; }

project_name() {
  local n; n=$(cfg_project)
  if [ -n "$n" ]; then printf '%s' "$n"; else basename "$ROOT"; fi
}

cfg_keys() {
  awk '
    /^sandboxes:/ {insb=1; next}
    insb && /^[^ ]/ {insb=0}
    insb && /^  [A-Za-z0-9][A-Za-z0-9._-]*: *$/ {k=$1; sub(/:$/,"",k); print k}
  ' "$CFG"
}

cfg_field() { # <key> <field>
  awk -v key="$1" -v field="$2" '
    /^sandboxes:/ {insb=1; next}
    insb && /^[^ ]/ {insb=0}
    insb && $0=="  " key ":" {inkey=1; next}
    inkey && /^  [^ ]/ {inkey=0}
    inkey && index($0, "    " field ":")==1 {
      v=substr($0, length("    " field ":")+1)
      gsub(/^ +| +$/, "", v); print v; exit
    }
  ' "$CFG" | unquote
}

cfg_default_key() {
  awk '
    /^sandboxes:/ {insb=1; next}
    insb && /^[^ ]/ {insb=0}
    insb && /^  [A-Za-z0-9][A-Za-z0-9._-]*: *$/ {k=$1; sub(/:$/,"",k); if (first=="") first=k; cur=k}
    insb && /^    default: true *$/ {def=cur}
    END {if (def!="") print def; else print first}
  ' "$CFG"
}

cfg_has_secret() { # <key> <service>
  local v
  v=$(awk -v key="$1" -v svc="$2" '
    /^sandboxes:/ {insb=1; next}
    insb && /^[^ ]/ {insb=0}
    insb && $0=="  " key ":" {inkey=1; next}
    inkey && /^  [^ ]/ {inkey=0; insec=0}
    inkey && /^    secrets:/ {
      if (index($0, "[")>0 && index($0, svc)>0) {print "y"; exit}
      insec=1; next
    }
    insec && /^      - / {s=$0; sub(/^ +- +/,"",s); gsub(/^ +| +$/,"",s); if (s==svc) {print "y"; exit}; next}
    insec {insec=0}
  ' "$CFG")
  [ "$v" = "y" ]
}

# ---- identity & naming (mirror of identity.ts / sandbox.ts) --------------------------

ident_id() {
  local id
  if [ -f "$IDF" ]; then
    id=$(awk -F': *' '$1=="id" {print $2; exit}' "$IDF" | unquote)
    if [ -n "$id" ]; then printf '%s' "$id"; return; fi
  fi
  id=$(od -An -N4 -tx4 /dev/urandom | tr -d ' \n' | cut -c1-5)
  printf 'id: %s\n' "$id" > "$IDF"
  grep -qx 'identity.yaml' "$ROOT/.sandbox/.gitignore" 2>/dev/null \
    || printf 'identity.yaml\n' >> "$ROOT/.sandbox/.gitignore"
  printf '%s' "$id"
}

sanitize() {
  local s
  s=$(printf '%s' "$1" | sed -E 's/[^A-Za-z0-9.+-]+/-/g; s/^[^A-Za-z0-9]+//; s/-+$//')
  if [ -n "$s" ]; then printf '%s' "$s"; else printf 'sandbox'; fi
}

require_key() { # [key] -> key (the default entry when omitted)
  local key="${1:-}"
  if [ -z "$key" ]; then key=$(cfg_default_key); fi
  [ -n "$key" ] || die "the recipe has no sandboxes"
  cfg_keys | grep -qx -- "$key" || die "unknown sandbox key \"$key\" (known: $(cfg_keys | tr '\n' ' '))"
  printf '%s' "$key"
}

instance_name() { # <key>
  printf '%s-%s-%s' "$(sanitize "$(project_name)")" "$(sanitize "$1")" "$(ident_id)"
}

resolve_target() { # <key-or-instance> — a recipe key derives; anything else is literal
  if cfg_keys | grep -qx -- "$1"; then instance_name "$1"; else printf '%s' "$1"; fi
}

instance_exists() { "$SBX" ls 2>/dev/null | awk -v n="$1" '$1==n {f=1} END {exit !f}'; }

# ---- workspace paths ------------------------------------------------------------------

# $ROOT in Git Bash is /<drive>/path — exactly the in-sandbox mount path on Windows;
# on macOS/Linux host and sandbox paths match as-is.
clone_workdir() { # <instance> — the private clone's path inside the sandbox
  local d
  d=$("$SBX" exec "$1" bash -lc 'find /home/agent -maxdepth 3 -name .git | head -1')
  [ -n "$d" ] || die "no git clone found inside $1"
  dirname "$d"
}

workdir_for() { # <key-or-instance> <instance>
  if cfg_keys | grep -qx -- "$1" && [ "$(cfg_field "$1" mount)" != "clone" ]; then
    printf '%s' "$ROOT"
  else
    clone_workdir "$2"
  fi
}

# ---- image pipeline & lifecycle (mirror of images.ts / ops.ts) ------------------------

build_image() { # <key> — no-op without a dockerfile
  local df img ctx tar
  df=$(cfg_field "$1" dockerfile); img=$(cfg_field "$1" image)
  if [ -z "$df" ] || [ -z "$img" ]; then return 0; fi
  ctx=$(cfg_field "$1" context); [ -n "$ctx" ] || ctx="."
  (cd "$ROOT" && docker build --pull -t "$img" -f ".sandbox/$df" "$ctx")
  tar=$(mktemp -t sbx-tmpl-XXXXXX)
  docker save "$img" -o "$tar"
  "$SBX" template load "$tar"
  rm -f "$tar"
}

refresh_image() { # <key> — FR-053: a rebuild starts from the freshest obtainable image.
  # Best-effort throughout: under set -euo pipefail every step must fail soft — a
  # refresh that cannot happen falls back to the cached image, never aborts the rebuild.
  local df img agent tar
  df=$(cfg_field "$1" dockerfile); img=$(cfg_field "$1" image)
  if [ -n "$df" ]; then return 0; fi                      # build_image pulls the base
  if [ -n "$img" ]; then
    # Pull + reload; never remove — a local-only image would be unrecoverable.
    if docker pull "$img"; then
      tar=$(mktemp -t sbx-tmpl-XXXXXX)
      if docker save "$img" -o "$tar" && "$SBX" template load "$tar"; then :; else
        printf 'sbx.sh: could not reload %s — rebuilding from the cached image\n' "$img" >&2
      fi
      rm -f "$tar"
    else
      printf 'sbx.sh: could not pull %s — rebuilding from the cached image\n' "$img" >&2
    fi
    return 0
  fi
  # Default agent image: drop the cached registry templates so create re-pulls.
  agent=$(cfg_field "$1" agent)
  { "$SBX" template ls 2>/dev/null || true; } | awk -v a="$agent" 'NR>1 && $1=="docker/sandbox-templates" && index($4, a)==1 {print $1 ":" $2}' | sort -u |
    while read -r t; do "$SBX" template rm "$t" || true; done
}

create_instance() { # <key>
  local key="$1" inst agent img
  inst=$(instance_name "$key")
  agent=$(cfg_field "$key" agent); [ -n "$agent" ] || die "sandboxes.$key.agent missing"
  img=$(cfg_field "$key" image)
  local args=(create --name "$inst")
  [ "$(cfg_field "$key" mount)" = "clone" ] && args+=(--clone)
  [ -n "$img" ] && args+=(-t "$img")
  "$SBX" "${args[@]}" "$agent" "$ROOT"
}

provision_recipe_secrets() { # <key> <instance> — best-effort, github only (the cached chain)
  if cfg_has_secret "$1" github; then
    if ! "$SBX" secret ls 2>/dev/null | awk -v i="$2" '($1=="(global)" || $1==i) && $3=="github" {f=1} END {exit !f}'; then
      cmd_secret_github "$2" || printf 'sbx.sh: github secret not provisioned — run: bash %s secret-github %s\n' "$0" "$2" >&2
    fi
  fi
}

# ---- secret chain (FR-051: ~/.sbx blobs shared with the extension) ---------------------

read_blob() { # <entry> — decrypt ~/.sbx/<entry>.github.dpapi (Windows DPAPI)
  local f="$HOME/.sbx/$1.github.dpapi" v
  [ -f "$f" ] || return 1
  command -v powershell.exe >/dev/null 2>&1 || return 1
  v=$(SBX_BLOB_PATH="$(cygpath -w "$f" 2>/dev/null || printf '%s' "$f")" powershell.exe \
        -NoProfile -NonInteractive -Command \
        '$ErrorActionPreference="Stop"; $raw=(Get-Content -LiteralPath $env:SBX_BLOB_PATH -Raw).Trim(); $ss=ConvertTo-SecureString -String $raw; $c=New-Object System.Net.NetworkCredential("", $ss); [Console]::Out.Write($c.Password)' \
        2>/dev/null | tr -d '\r\n')
  [ -n "$v" ] || return 1
  printf '%s' "$v"
}

github_pat() { # resolve: project blob -> shared blob -> env (CI/automation)
  read_blob "$(sanitize "$(project_name)")" && return 0
  read_blob shared && return 0
  if [ -n "${GITHUB_SANDBOX_PAT:-}" ]; then printf '%s' "$GITHUB_SANDBOX_PAT"; return 0; fi
  return 1
}

cmd_secret_github() { # [key|runner]
  local key inst pat
  if [ -n "${1:-}" ]; then
    inst=$(resolve_target "$1")
  else
    key=$(require_key "")
    inst=$(instance_name "$key")
  fi
  if ! pat=$(github_pat); then
    {
      printf 'sbx.sh: no GitHub PAT provisioned on this machine. NEVER paste the value into an agent session.\n'
      printf 'Provision once, outside any session:\n'
      printf '  workstation (PowerShell):\n'
      printf '    powershell -NoProfile -Command "New-Item -ItemType Directory -Force $env:USERPROFILE\\.sbx | Out-Null; Read-Host -AsSecureString '"'"'Sandbox GitHub PAT'"'"' | ConvertFrom-SecureString | Set-Content $env:USERPROFILE\\.sbx\\%s.github.dpapi"\n' "$(sanitize "$(project_name)")"
      printf '  automation (CI/cloud): inject GITHUB_SANDBOX_PAT from the platform secret store.\n'
    } >&2
    return 1
  fi
  printf '%s' "$pat" | "$SBX" secret set "$inst" github
  printf '%s' "$pat" | "$SBX" exec -i "$inst" bash -lc 'gh auth login --with-token' >/dev/null 2>&1 || true
  printf 'github secret provisioned for %s\n' "$inst"
}

# ---- commands --------------------------------------------------------------------------

cmd_status() {
  local p id
  p=$(sanitize "$(project_name)"); id=$(ident_id)
  "$SBX" ls | awk -v p="$p" -v id="$id" 'NR==1 || (index($1, p "-")==1 && index($1, "-" id)>0)'
}

cmd_connect() {
  local key inst
  key=$(require_key "${1:-}")
  inst=$(instance_name "$key")
  if ! instance_exists "$inst"; then
    if [ -n "$(cfg_field "$key" dockerfile)" ]; then build_image "$key"; fi
    create_instance "$key"
    provision_recipe_secrets "$key" "$inst"
  fi
  exec "$SBX" run "$inst"
}

cmd_stop() {
  local key inst
  key=$(require_key "${1:-}")
  inst=$(instance_name "$key")
  "$SBX" stop "$inst"
}

cmd_rm() {
  local key inst
  [ "${2:-}" = "--force" ] || die "sbx rm destroys in-sandbox state (tools, history; clone-mode work too) — re-run with --force; the recipe stays, recreate with connect"
  key=$(require_key "${1:-}")
  inst=$(instance_name "$key")
  "$SBX" rm --force "$inst"
}

cmd_rebuild() {
  local key inst
  key=$(require_key "${1:-}")
  inst=$(instance_name "$key")
  build_image "$key"
  if instance_exists "$inst"; then
    printf 'recreating %s (in-sandbox state is lost; the host workspace survives on direct mount)\n' "$inst"
    "$SBX" rm --force "$inst"
  fi
  refresh_image "$key"    # after rm: a template referenced by a live instance could refuse removal
  create_instance "$key"
  provision_recipe_secrets "$key" "$inst"
  printf 'rebuilt %s\n' "$inst"
}

cmd_exec() { # <key|runner> -- <cmd...>
  local target="${1:?usage: exec <key|runner> -- <cmd...>}"; shift
  [ "${1:-}" = "--" ] && shift
  [ $# -gt 0 ] || die "exec needs a command after --"
  local inst wd
  inst=$(resolve_target "$target")
  wd=$(workdir_for "$target" "$inst")
  exec "$SBX" exec -w "$wd" "$inst" "$@"
}

cmd_task() { # <key|runner> "<prompt>" [--bg|--json]
  local target="${1:?usage: task <key|runner> \"<prompt>\" [--bg|--json]}"
  local prompt="${2:?task needs a prompt}"
  shift 2
  local bg=0 json=0
  while [ $# -gt 0 ]; do
    case "$1" in
      --bg) bg=1 ;;
      --json) json=1 ;;
      *) die "unknown task flag $1" ;;
    esac
    shift
  done
  local inst wd
  inst=$(resolve_target "$target")
  wd=$(workdir_for "$target" "$inst")
  # --dangerously-skip-permissions is sanctioned ONLY because execution is inside the
  # microVM (kernel isolation + credential proxy). Never copy this flag to host runs.
  if [ "$bg" = 1 ]; then
    local slug; slug="task-$(date +%Y%m%d-%H%M%S)"
    printf '%s' "$prompt" | "$SBX" exec -i "$inst" bash -lc "cat > /tmp/$slug.prompt"
    "$SBX" exec -d -w "$wd" "$inst" bash -lc "claude -p \"\$(cat /tmp/$slug.prompt)\" --dangerously-skip-permissions > /tmp/$slug.log 2>&1"
    printf 'dispatched %s on %s\n' "$slug" "$inst"
    printf 'poll: bash %s exec %s -- tail -n 40 /tmp/%s.log\n' "$0" "$target" "$slug"
  elif [ "$json" = 1 ]; then
    local out
    out=$("$SBX" exec -w "$wd" "$inst" claude -p "$prompt" --output-format json --dangerously-skip-permissions)
    printf '%s\n' "$out"
    printf '%s' "$out" | grep -o '"total_cost_usd":[0-9.]*' >&2 || true
  else
    exec "$SBX" exec -w "$wd" "$inst" claude -p "$prompt" --output-format text --dangerously-skip-permissions
  fi
}

cmd_runner_create() { # <slug> [-m 8g] [--cpus 4] — ephemeral clone runner off the default sandbox
  local slug="${1:?usage: runner-create <slug> [-m 8g] [--cpus N]}"; shift
  printf '%s' "$slug" | grep -Eq '^[a-z0-9][a-z0-9-]*$' || die "slug must be lowercase letters/digits/dashes"
  local mem="8g" cpus="4"
  while [ $# -gt 0 ]; do
    case "$1" in
      -m) mem="${2:?-m needs a value}"; shift ;;
      --cpus) cpus="${2:?--cpus needs a value}"; shift ;;
      *) die "unknown runner-create flag $1" ;;
    esac
    shift
  done
  local key inst rname agent img
  key=$(cfg_default_key); [ -n "$key" ] || die "the recipe has no sandboxes"
  inst=$(instance_name "$key")
  rname="$inst-p$slug"
  instance_exists "$rname" && die "$rname already exists"
  agent=$(cfg_field "$key" agent)
  img=$(cfg_field "$key" image)
  # The clone follows the host's checked-out ref AT CREATE TIME — check out the intended
  # base first. Never written into the recipe: runners are ephemeral by name contract.
  local args=(create --clone --name "$rname" -m "$mem" --cpus "$cpus")
  [ -n "$img" ] && args+=(-t "$img")
  "$SBX" "${args[@]}" "$agent" "$ROOT"
  provision_recipe_secrets "$key" "$rname"
  printf 'runner:   %s\n' "$rname"
  printf 'base ref: %s\n' "$(git -C "$ROOT" rev-parse --abbrev-ref HEAD 2>/dev/null || echo '?')"
  printf 'clone:    %s\n' "$(clone_workdir "$rname" 2>/dev/null || echo '<starting — query later via: exec '"$rname"' -- pwd>')"
}

cmd_runner_rm() { # <runner> [--force] — guarded against losing unharvested work
  local rname="${1:?usage: runner-rm <runner> [--force]}"
  local idp; idp="-$(ident_id)-p"
  case "$rname" in
    *"$idp"*) ;;
    *) die "\"$rname\" is not one of this working copy's runners (expected ...$idp<slug>)" ;;
  esac
  if [ "${2:-}" != "--force" ]; then
    "$SBX" exec "$rname" true >/dev/null 2>&1 || true # auto-start so the clone's git daemon serves
    if git -C "$ROOT" fetch "sandbox-$rname" >/dev/null 2>&1; then
      printf 'fetched sandbox-%s — work is preserved on the host\n' "$rname"
    else
      die "could not fetch sandbox-$rname; push/fetch its work first, or pass --force to discard it"
    fi
  fi
  "$SBX" rm --force "$rname"
  printf 'removed %s\n' "$rname"
}

cmd_runners() {
  local p id
  p=$(sanitize "$(project_name)"); id=$(ident_id)
  "$SBX" ls | awk -v p="$p" -v id="$id" 'NR==1 || (index($1, p "-")==1 && index($1, "-" id "-p")>0)'
}

usage() { sed -n '/^# Commands:/,/^set -euo/p' "$0" | sed '$d'; }

cmd="${1:-help}"
shift || true
case "$cmd" in
  name)          key=$(require_key "${1:-}"); instance_name "$key"; echo ;;
  status)        cmd_status ;;
  connect)       cmd_connect "$@" ;;
  stop)          cmd_stop "$@" ;;
  rm)            cmd_rm "$@" ;;
  rebuild)       cmd_rebuild "$@" ;;
  exec)          cmd_exec "$@" ;;
  task)          cmd_task "$@" ;;
  runner-create) cmd_runner_create "$@" ;;
  runner-rm)     cmd_runner_rm "$@" ;;
  runners)       cmd_runners ;;
  secret-github) cmd_secret_github "${1:-}" ;;
  version)       printf 'Sandbox Console project CLI v%s\n' '0.2.0' ;;
  help|--help|-h) usage ;;
  *) usage; die "unknown command \"$cmd\"" ;;
esac
